name: Build C++ Exercises

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Compile exercise01
        run: g++ -o exercise01.exe exercise01.cpp

      - name: Compile exercise02
        run: g++ -o exercise02.exe exercise02.cpp

      - name: Compile exercise03
        run: g++ -o exercise03.exe exercise03.cpp

      - name: Compile exercise04
        run: g++ -o exercise04.exe exercise04.cpp

      - name: Upload compiled executables
        uses: actions/upload-artifact@v4
        with:
          name: compiled-exes
          path: |
            exercise01.exe
            exercise02.exe
            exercise03.exe
            exercise04.exe
